#!/bin/sh

set -e

pkg=buddycloud-server-java

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/config.pgsql ]; then
	. /usr/share/dbconfig-common/dpkg/config.pgsql
	dbc_go "$pkg" "$@"
fi

exit 0
