#!/bin/sh

set -e

pkg=buddycloud-http-api

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then
	adduser --system --quiet --group --disabled-password \
		--gecos "Buddycloud XMPP channel service" \
		--no-create-home --home "/var/run/$pkg" \
		buddycloud
fi

#DEBHELPER#
