#!/bin/sh

set -e

pkg=buddycloud-http-api

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then
	adduser --system --quiet --group --disabled-password \
		--gecos "Buddycloud XMPP channel service" \
		--no-create-home --home "/var/run/$pkg" \
		buddycloud
fi

# Create public dir for primus
mkdir -p /usr/share/buddycloud-http-api/public/scripts
chown -R buddycloud:buddycloud /usr/share/buddycloud-http-api/public/scripts 

#DEBHELPER#
