echo #JDBC_DB_HOST#:#JDBC_DB_PORT#:#TIGASE_JDBC_DB_NAME#:#TIGASE_JDBC_DB_USER#:#TIGASE_JDBC_DB_PASS# > ~/.pgpass
chmod 600 ~/.pgpass
psql -w -U #TIGASE_JDBC_DB_USER# -d #TIGASE_JDBC_DB_NAME# -h #JDBC_DB_HOST# -p #JDBC_DB_PORT# -c "SELECT TigAddUserPlainPw('#HOSTING_ADMIN_XMPP_CLIENT#', '#HOSTING_ADMIN_XMPP_PASS#');" | true
rm ~/.pgpass
