#!/bin/bash
source /srv/build/commonrc.sh
source /srv/build/mediaserverrc.sh
source /srv/build/buddycloudserverrc.sh
source /srv/build/hostingrc.sh
source /src/build/tigaserc.sh

env | cut -d'=' -f1 | while read KEY; do
  VALUE=${!KEY}
  KEY="#$KEY#"
  sed -i "s|$KEY|$VALUE|g" buddycloud-hosting.cfg 2&>1 > /dev/null
done
