#!/bin/bash

sed -i "s/#HTTP_API_ADDRESS#/$API_PORT_9123_TCP_ADDR/g" /etc/apache2/sites-enabled/000-default
sed -i "s/#HOSTING_ADDRESS#/$HOSTING_PORT_3000_TCP_ADDR/g" /etc/apache2/sites-enabled/000-default

