#!/bin/bash

pkg=buddycloud-pusher

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm.pgsql  ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.pgsql
    dbc_go "$pkg" "$@" || true
fi

update-rc.d -f buddycloud-pusher remove

#DEBHELPER#