#!/bin/bash
source /srv/build/commonrc.sh
source /srv/build/buddycloudserverrc.sh
source /srv/build/hostingrc.sh

env | cut -d'=' -f1 | while read KEY; do
  VALUE=${!KEY}
  KEY="#$KEY#"
  sed -i "s|$KEY|$VALUE|g" configuration.properties 2&>1 > /dev/null
  sed -i "s|$KEY|$VALUE|g" external-domain-checker 2&>1 > /dev/null
done
